name: my_game
description: Multiplayer Guess Game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  nearby_connections: ^3.1.2
  # تحديد الإصدار بدقة بدون علامة ^ لمنع التحديث التلقائي
  permission_handler: 11.2.0
  
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
