name: Build Flutter Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # استخدام إصدار 3.13.9 بدلاً من channel: 'stable'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Generate Flutter Structure
        run: flutter create --project-name my_game --org com.abdullah .

      - name: Fix Plugin Namespaces (AGP 8.0+)
        run: |
          echo "
          subprojects {
              afterEvaluate { project ->
                  if (project.hasProperty('android')) {
                      project.android {
                          if (namespace == null) {
                              namespace project.group
                          }
                      }
                  }
              }
          }" >> android/build.gradle

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: game-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
